# -*- coding: utf-8 -*-
from views import info
from PyQt5 import QtCore, QtGui, QtWidgets


class centerInfo(QtWidgets.QDialog):
    def __init__(self, parent, center_id):
        super(centerInfo, self).__init__(parent)
        self.setupUi(self)
        info.fill(self, 3, center_id)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name_of_info_requester = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.name_of_info_requester.setFont(font)
        self.name_of_info_requester.setAlignment(QtCore.Qt.AlignCenter)
        self.name_of_info_requester.setObjectName("name_of_info_requester")
        self.verticalLayout_2.addWidget(self.name_of_info_requester)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.event_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.event_label.setFont(font)
        self.event_label.setAlignment(QtCore.Qt.AlignCenter)
        self.event_label.setObjectName("event_label")
        self.horizontalLayout.addWidget(self.event_label)

        self.volunteer_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.volunteer_label.setFont(font)
        self.volunteer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.volunteer_label.setObjectName("volunteer_label")
        self.horizontalLayout.addWidget(self.volunteer_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.events_table = QtWidgets.QTableWidget(Form)
        self.events_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.events_table.setObjectName("events_table")
        self.events_table.setColumnCount(2)
        self.events_table.setRowCount(0)
        self.events_table.setHorizontalHeaderItem(0, QtWidgets.QTableWidgetItem())
        self.events_table.setHorizontalHeaderItem(1, QtWidgets.QTableWidgetItem())
        self.horizontalLayout_2.addWidget(self.events_table)
        self.volunteers_table = QtWidgets.QTableWidget(Form)
        self.volunteers_table.setObjectName("tableWidget")
        self.volunteers_table.setColumnCount(2)
        self.volunteers_table.setRowCount(0)
        self.volunteers_table.setHorizontalHeaderItem(0, QtWidgets.QTableWidgetItem())
        self.volunteers_table.setHorizontalHeaderItem(1, QtWidgets.QTableWidgetItem())
        self.horizontalLayout_2.addWidget(self.volunteers_table)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.organization_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.organization_label.setFont(font)
        self.organization_label.setAlignment(QtCore.Qt.AlignCenter)
        self.organization_label.setObjectName("organization_label")
        self.horizontalLayout.addWidget(self.organization_label)
        self.org_table = QtWidgets.QTableWidget(Form)
        self.org_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.org_table.setObjectName("org_table")
        self.org_table.setColumnCount(2)
        self.org_table.setRowCount(0)
        self.org_table.setHorizontalHeaderItem(0, QtWidgets.QTableWidgetItem())
        self.org_table.setHorizontalHeaderItem(1, QtWidgets.QTableWidgetItem())
        self.horizontalLayout_2.addWidget(self.org_table)
        #
        self.events_table.horizontalHeader().setCascadingSectionResizes(True)
        self.events_table.horizontalHeader().setStretchLastSection(False)
        self.events_table.verticalHeader().setVisible(False)
        self.events_table.verticalHeader().setCascadingSectionResizes(True)
        self.events_table.verticalHeader().setSortIndicatorShown(True)
        self.events_table.verticalHeader().setStretchLastSection(False)
        self.events_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        #
        self.volunteers_table.horizontalHeader().setCascadingSectionResizes(True)
        self.volunteers_table.horizontalHeader().setStretchLastSection(False)
        self.volunteers_table.verticalHeader().setVisible(False)
        self.volunteers_table.verticalHeader().setCascadingSectionResizes(True)
        self.volunteers_table.verticalHeader().setSortIndicatorShown(True)
        self.volunteers_table.verticalHeader().setStretchLastSection(False)
        self.volunteers_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        #
        self.org_table.horizontalHeader().setCascadingSectionResizes(True)
        self.org_table.horizontalHeader().setStretchLastSection(False)
        self.org_table.verticalHeader().setVisible(False)
        self.org_table.verticalHeader().setCascadingSectionResizes(True)
        self.org_table.verticalHeader().setSortIndicatorShown(True)
        self.org_table.verticalHeader().setStretchLastSection(False)
        self.org_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        #

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name_of_info_requester.setText(_translate("Form", "Name"))
        self.event_label.setText(_translate("Form", "Мероприятия"))
        self.volunteer_label.setText(_translate("Form", "Волонтеры"))
        self.organization_label.setText(_translate("Form", "Организации"))
        self.events_table.horizontalHeaderItem(0).setText(_translate("Form", "id"))
        self.events_table.horizontalHeaderItem(1).setText(_translate("Form", "Название"))
        self.volunteers_table.horizontalHeaderItem(0).setText(_translate("Form", "id"))
        self.volunteers_table.horizontalHeaderItem(1).setText(_translate("Form", "ФИО"))
        self.org_table.horizontalHeaderItem(0).setText(_translate("Form", "id"))
        self.org_table.horizontalHeaderItem(1).setText(_translate("Form", "Название"))
